### PR TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### PR DESCRIPTION
**Pull request by centerax**
ref https://github.com/magento-engcom/php-7.2-support/issues/7

### CODE REVIEW

**Comment by centerax** [comment]
#distributed-dc

**Comment by centerax** [comment]
#distributed-cd

**Comment by buskamuza** [comment]
Sorry, this has already fixed in the PR https://github.com/magento-engcom/php-7.2-support/pull/97 - https://github.com/magento-engcom/php-7.2-support/blob/libs-upgrade/setup/src/Magento/Setup/Test/Unit/Module/I18n/Pack/GeneratorTest.php#L105
Issue #7 was in progress and assigned to one of our team members.

**Comment by centerax** [comment]
ok

**Pull request closed without merging**
